platform :ios, '7.0'
target ‘SwordClient’ do

    pod 'SDVersion', '2.5.2'

# Network
    pod 'AFNetworking', '3.1.0'
    pod 'AFNetworkActivityLogger', :git => 'https://github.com/AFNetworking/AFNetworkActivityLogger.git', :branch => '3_0_0'
    pod 'MJRefresh', '3.0.7'
    pod 'SDWebImage', '3.7.6'
    pod 'MBProgressHUD', '0.9.1'
    pod 'MJExtension', '3.0.10'
    pod 'HexColors', '2.2.0'
    pod 'IQKeyboardManager'

# Autolayout
    pod 'Masonry', '1.0.2'
    
# 集成QQ
    pod 'UMengUShare/Social/QQ'
# 集成微信
    pod 'UMengUShare/Social/WeChat'
end
